# Generated by Django 2.0.2 on 2018-10-23 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('AccountNumber', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Balance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BankUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=250)),
                ('otp_value', models.CharField(default='0', editable=False, max_length=16)),
                ('type_of_user', models.CharField(choices=[('R', 'Regular Employee'), ('S', 'System Manager'), ('A', 'Admin'), ('I', 'Individual Customer'), ('O', 'Organization')], max_length=1)),
            ],
            options={
                'permissions': (('is_External_User', 'Customer of bank'), ('is_Internal_User', 'Employee has permissions to access User data')),
            },
        ),
        migrations.AddField(
            model_name='account',
            name='AccountHolder',
            field=models.ForeignKey(null=True, on_delete=True, to='SecureBank.BankUser'),
        ),
    ]
