# Generated by Django 2.0.2 on 2018-10-30 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SecureBank', '0002_auto_20181029_0705'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoggedInUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=32, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_in_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Status',
            field=models.CharField(choices=[('O', 'OTP'), ('A', 'Internal User Approval required'), ('P', 'Complete'), ('R', 'Rejected by Internal User'), ('E', 'Error occured during transaction')], max_length=1),
        ),
    ]
