# Generated by Django 2.0.2 on 2018-10-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecureBank', '0003_auto_20181030_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggedinuser',
            name='name',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
