# Generated by Django 2.1.2 on 2018-10-30 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecureBank', '0004_loggedinuser_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankuser',
            options={},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Status',
            field=models.CharField(choices=[('O', 'OTP required'), ('A', 'Approval required'), ('P', 'Processed'), ('R', 'Rejected'), ('E', 'Unsuccessful')], editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Type',
            field=models.CharField(choices=[('C', 'Credit'), ('D', 'Debit'), ('T', 'Transfer')], default='T', editable=False, max_length=1),
        ),
    ]
