# Generated by Django 2.1.2 on 2018-11-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecureBank', '0005_auto_20181030_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='Amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Status',
            field=models.CharField(choices=[('O', 'OTP required'), ('A', 'Approval required'), ('P', 'Processed'), ('R', 'Rejected'), ('E', 'Unsuccessful')], max_length=1),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Type',
            field=models.CharField(choices=[('C', 'Credit'), ('D', 'Debit'), ('T', 'Transfer')], default='T', max_length=1),
        ),
    ]
